module.exports = Object.freeze({
    USERNAME_SELECTOR: '#mat-input-0',
    PASSWORD_SELECTOR: '#password',
    SUBMIT_BUTTON_SELECTOR: '.button-orange.wide',
    PIN_INPUT_SELECTOR: '#pin',
    PIN_BUTTON_SELECTOR: '.button-orange.wide',
    ORDER_NAV_SELECTOR: '.icon.icon-bookmark',
    SERACH_BOX_SELECTOR: '.omnisearch input',
    SEARCH_RESULT_SELECTOR: '.selected .tradingsymbol',
    SHORT_LISTED_RESULT_SELECTOR: '#app > div.container.wrapper > div > div > div > div.instruments > div > div.vddl-draggable.instrument.selected > div > div > span.symbol > span > span',
    TRIGGER_PRICE_SELECTOR: 'input[label="Trigger price"]',
    TRIGGER_QUANTITY_SELECTOR: 'input[label="Qty."]',
    TRIGGER_PRICE2_SELECTOR: 'input[label="Price"]',
    FINAL_SUBMIT_BUTTON_SELECTOR: '.actions > button[type="submit"]',
    EXIST_SELECTOR: '.marketwatch-sidebar > .omnisearch',
    GTT_SELECTOR: '.icon.icon-book',
    GTT_ORDER_SELECTOR: '.page-nav > a[href="/orders/gtt"]',
});